all:
  children:
    servers:
      hosts:
        thinkpad:
          ansible_host: homelab
          ansible_user: philipnickel
    clients:
      hosts:
        macbook:
          ansible_host: localhost
          ansible_connection: local
