---
# Settings for Nomad server nodes

consul_server: true
nomad_server: true

# Consul server config
consul_bootstrap_expect: 1
consul_retry_join: []

# Nomad server config
nomad_bootstrap_expect: 1

# Traefik runs on server
traefik_enabled: true
